# Generated by Django 6.0.7 on 2026-07-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Nome da coluna na consulta BI. Ex.: ImpostoISS_IPTU', max_length=80, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AjusteManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inclusao', 'Inclusão manual'), ('exclusao', 'Exclusão manual'), ('reclassificacao', 'Reclassificar competência')], max_length=20)),
                ('cd_empresa', models.CharField(max_length=10)),
                ('cd_empreendimento', models.CharField(blank=True, max_length=11)),
                ('cd_nucleo', models.CharField(blank=True, max_length=3)),
                ('cd_centro', models.CharField(blank=True, max_length=15)),
                ('data_competencia', models.DateField(help_text='Mês de competência no BI (será convertido para EOMONTH).')),
                ('data_lancamento', models.DateField(blank=True, help_text='Data original ou futura do lançamento (opcional).', null=True)),
                ('valor', models.FloatField(help_text='Valor positivo ou negativo conforme o ajuste.')),
                ('chave_orc', models.TextField(blank=True, help_text='Referência ao lançamento original, se houver.')),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='controladoria.medida')),
            ],
            options={
                'verbose_name': 'Ajuste Manual',
                'verbose_name_plural': 'Ajustes Manuais',
                'ordering': ['-data_competencia', 'medida__ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ano_minimo', models.PositiveIntegerField(default=2024, help_text='Filtra YEAR(Data) >= este valor.')),
                ('funcao_agregacao', models.CharField(choices=[('sum', 'Soma (SUM)'), ('count', 'Contagem (COUNT)'), ('avg', 'Média (AVG)'), ('max', 'Máximo (MAX)'), ('min', 'Mínimo (MIN)')], default='sum', max_length=10)),
                ('campo_agregacao', models.CharField(default='valor', help_text='Campo numérico da fato. Ex.: valor', max_length=50)),
                ('condicoes', models.JSONField(blank=True, default=list, help_text='Filtros sobre alias f. Ex.: [{"campo":"Assunto","operador":"in","valores":["impostos"]}]')),
                ('joins', models.JSONField(blank=True, default=list, help_text='Joins e filtros em dimensões. Ex.: DimSubGrupo com filtros em nmSubGrupo.')),
                ('group_by', models.JSONField(blank=True, default=list, help_text='Campos de agrupamento. Use eomonth(Data) para competência mensal.')),
                ('sql_extra', models.TextField(blank=True, help_text='Cláusula WHERE adicional (SQL bruto). Prefixe com AND.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='controladoria.medida')),
            ],
            options={
                'verbose_name': 'Regra de Medida',
                'verbose_name_plural': 'Regras de Medida',
                'ordering': ['medida__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ExcecaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('excluir', 'Excluir da regra'), ('incluir', 'Forçar inclusão na regra')], default='excluir', max_length=10)),
                ('chave_orc', models.TextField(blank=True, help_text='ChaveOrc do lançamento na fato (identificador preferencial).')),
                ('cd_empresa', models.CharField(blank=True, max_length=10)),
                ('cd_empreendimento', models.CharField(blank=True, max_length=11)),
                ('cd_nucleo', models.CharField(blank=True, max_length=3)),
                ('cd_centro', models.CharField(blank=True, max_length=15)),
                ('data', models.DateField(blank=True, help_text='Data original do lançamento.', null=True)),
                ('assunto', models.CharField(blank=True, max_length=150)),
                ('classificacao', models.CharField(blank=True, max_length=150)),
                ('cliente_fornecedor', models.CharField(blank=True, max_length=150)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='controladoria.regramedida')),
            ],
            options={
                'verbose_name': 'Exceção de Lançamento',
                'verbose_name_plural': 'Exceções de Lançamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
