# Generated by Django 6.0.7 on 2026-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustemanual',
            name='data_original',
            field=models.DateField(blank=True, help_text='Data do lançamento excluído antes do ajuste.', null=True),
        ),
        migrations.AddField(
            model_name='ajustemanual',
            name='valor_original',
            field=models.FloatField(blank=True, help_text='Valor do lançamento excluído antes do ajuste.', null=True),
        ),
    ]
