# Generated by Django 6.0.7 on 2026-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0002_ajuste_valores_originais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=3, unique=True)),
                ('segmento', models.CharField(choices=[('SPE', 'SPE'), ('CON', 'CON')], max_length=3)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['empresa'],
            },
        ),
    ]
