# Generated by Django 6.0.7 on 2026-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
