# Generated by Django 6.0.7 on 2026-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0004_empresa_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('competencia', models.DateField(help_text='Data de referência da competência (ex.: último dia do mês).')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-competencia', 'tipo'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(help_text='Código único da empresa (até 3 caracteres).', max_length=3, unique=True),
        ),
    ]
