# Generated by Django 6.0.7 on 2026-07-29 14:56

import django.db.models.deletion
from django.db import migrations, models


def migrar_tipos_competencia(apps, schema_editor):
    Competencia = apps.get_model('controladoria', 'Competencia')
    TipoCompetencia = apps.get_model('controladoria', 'TipoCompetencia')

    for item in Competencia.objects.exclude(tipo_nome='').exclude(tipo_nome__isnull=True):
        tipo_obj, _ = TipoCompetencia.objects.get_or_create(nome=item.tipo_nome.strip())
        item.tipo_id = tipo_obj.pk
        item.save(update_fields=['tipo_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0005_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Competência',
                'verbose_name_plural': 'Tipos de Competência',
                'ordering': ['nome'],
            },
        ),
        migrations.RenameField(
            model_name='competencia',
            old_name='tipo',
            new_name='tipo_nome',
        ),
        migrations.AddField(
            model_name='competencia',
            name='tipo',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='competencias',
                to='controladoria.tipocompetencia',
            ),
        ),
        migrations.RunPython(migrar_tipos_competencia, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='competencia',
            name='tipo_nome',
        ),
        migrations.AlterField(
            model_name='competencia',
            name='tipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='competencias',
                to='controladoria.tipocompetencia',
            ),
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={
                'ordering': ['-competencia', 'tipo__nome'],
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
            },
        ),
    ]
