# Generated by Django 6.0.7 on 2026-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0006_tipo_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='percentual_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de venda (0 a 100).', max_digits=5, null=True),
        ),
    ]
