# Generated by Django 6.0.7 on 2026-07-29 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0007_empresa_percentual_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_contrato', models.CharField(max_length=16, unique=True)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('cd_empresa', models.CharField(max_length=3)),
                ('contrato', models.CharField(blank=True, max_length=6)),
                ('situacao', models.CharField(blank=True, max_length=1)),
                ('cd_cliente', models.CharField(blank=True, max_length=4)),
                ('cliente', models.CharField(blank=True, max_length=50)),
                ('valor_tabela_primeira', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_tabela_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_venda_a_vista', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('liquidado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('percentual', models.FloatField(blank=True, null=True)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_corte', models.DateField(help_text='Data de corte usada na consulta de pagamentos.')),
                ('mes_fechamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ano_fechamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(help_text='Competência em que a comissão será paga.', on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='controladoria.competencia')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-criado_em'],
            },
        ),
    ]
