# Generated by Django 6.0.7 on 2026-09-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controladoria', '0009_comissao_data_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ (opcional).', max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SocioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de participação na empresa (0 a 100).', max_digits=5)),
                ('taxa_administracao', models.DecimalField(decimal_places=2, help_text='Taxa de administração (0 a 100).', max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='controladoria.empresa')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='controladoria.socio')),
            ],
            options={
                'verbose_name': 'Sócio × Empresa',
                'verbose_name_plural': 'Sócios × Empresas',
                'ordering': ['empresa__empresa', 'socio__nome'],
                'constraints': [models.UniqueConstraint(fields=('socio', 'empresa'), name='uniq_socio_empresa')],
            },
        ),
    ]
